#!/bin/sh
#
# Git pre-commit hook that runs cargo xtask precommit
# This ensures rustfmt is applied and clippy passes all checks
#
# To install this hook manually, run:
#   cp hooks/pre-commit .git/hooks/pre-commit
#   chmod +x .git/hooks/pre-commit
#
# Or use the xtask command:
#   cargo xtask hooks install

set -e

exec cargo xtask precommit
